[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128", "-C", "link-arg=--max-memory=4294967296"]

# set max memory to 512MB
# rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals,+simd128", "-C", "link-arg=--max-memory=536870912"]

[unstable]
build-std = ["panic_abort", "std"]