[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
egui-winit = { version = "0.22", default-features = false }
egui_tiles = "0.1"

log = "0.4"

parking_lot = "0.12.1"

raving-wgpu = { path = "../../raving-wgpu" }
waragraph-core = { path = "../lib" }

anyhow = "1.0"
ultraviolet = { version = "0.9", features = ["bytemuck", "f64", "mint"]}